catch cases without 'File:' at the start of image
Commonists/QICbot pull request #4
Opened 2022-05-31 19:58 UTC by mpeel

There was an error on 28 May:

Tagging File:Immeuble_Lengema_Kisangani.jpg
Traceback (most recent call last):
  File "qic2.py", line 627, in <module>
    unassessed, unassessedCat, "", "Bot: Tag as unassessed Quality Image Candidate"
  File "qic2.py", line 88, in doTagging
    print("Oops " + image.encode("utf-8") + " doesn't exist...")
TypeError: Can't convert 'bytes' object to str implicitly
CRITICAL: Exiting due to uncaught exception <class 'TypeError'>

The next line was:
Praha Stare Mesto Templova mriz.jpg|{{../Nomination|Steel gate of a passage between Templová and Králodvorská, Old Town, Prague, Czechia --[[User:JiriMatejicek|JiriMatejicek]] 15:48, 19 May 2022 (UTC)}}

This change hopefully works around this issue of a missing 'File:'?

2022-05-31 21:05 UTC, tacsipacsi requested changes

2022-05-31 21:05 UTC, tacsipacsi commented on qic2.py
> +				print("Error with" + str(image))
```suggestion
			print("Oops " + image + " doesn't exist...")
```
Didn’t test this, but based on the error message, it looks like the bot is running under Python3, and `image` is a `str` object (used to be `unicode` under Python2). String literals are also `str`s, so you can just skip encoding it. With this proposed change, it’ll stop working under Python2, but no one should use Python2 in 2022 anyways.

2022-05-31 21:05 UTC, tacsipacsi commented on qic2.py
>          if page.exists():
This breaks images with `Image:` namespace (totally legal alias), but it doesn’t add the namespace if the namespace occurs anywhere else in the file name (e.g. `This is a File: example.svg`). `pywikibot.FilePage` handles these as expected:
```suggestion
		try:
			page = pywikibot.FilePage(SITE, image)
		except ValueError:
			print("Oops " + image + " isn't a file...")
		else:
			if page.exists():
				# ... and the rest also indented one extra level
```

2022-06-03 20:08 UTC, mpeel commented
The changes look OK to me, they assume a bit more but should work. Being WP:BOLD and merging.

2022-06-03 20:08 UTC, merged